road_obstacles:
  - type: barrel
    s: 90.0
    lane: 0
    radius: 0.6

  - type: barrel
    s: 100.0
    lane: 1
    radius: 0.6
    
  # - type: barrel
  #   s: 155.0
  #   lane: 0
  #   radius: 0.6

  # - type: barrel
  #   s: 200.0
  #   lane: 1
  #   radius: 0.6


scenario:
  randomize_positions: false
  randomize_lanes: false